### ISSUE TITLE
luizgois.com.br está com redirect loop

### ISSUE THREAD

**Issue by gabrielhpugliese** [zoeiralabs/luiz#1]
Aqui nem entra e trava o Chrome:
![image](https://cloud.githubusercontent.com/assets/1252818/17345225/6c298ef6-58db-11e6-98c6-6a9fd2082ac2.png)

**Comment by rvalverde-luizalabs** [comment]
Vdd, loop infinito amiguinhos! 👍

**Comment by ghost** [comment]
acho que não deu certo o CNAME @jairhenrique :(

**Comment by gabrielhpugliese** [comment]
O que o Luiz falaria deste CNAME, hein?

**Comment by luizgois-luizalabs** [comment]
@gabrielhpugliese abre PR e arruma :)

**Comment by luizgois-luizalabs** [comment]
Resolvido
